version: '2.2'
services:
  elasticsearch:
    image: zhjs/es-with-ik:6.5.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker_cluster_zhjs
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9400:9200
    networks:
      - esnet
  elasticsearch2:
    image: zhjs/es-with-ik:6.5.0
    container_name: elasticsearch2
    environment:
      - cluster.name=docker_cluster_zhjs
      - bootstrap.memory_lock=true
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet:

